### ISSUE TITLE
Can PS-GAIL algorithm applied in this InteractionSimulator?

### ISSUE THREAD

**Issue by Gengmaosi** [sisl/InteractionSimulator#12]
As mentioned in the title, can the PS-GAIL algorithm applied in this InteractionSimulator? If can, which steps shall we follow?

**Comment by jamgochiana** [comment]
Yes! You would want to use the `intersim` environment for multi-agent RL, separate out the observations for each agent, and recombine the actions from the learned policy applied to each agent. For a repo that does GAIL for single-agent policies with this simulator, take a look at [github.com/sisl/InteractionImitation](http://github.com/sisl/InteractionImitation)
